create table if not exists todos
(
    id          bigint generated by default as identity primary key,
    name        varchar(255) not null,
    description varchar(255) not null,
    is_done     boolean      not null default false,
    created_at  timestamp    not null default now()
);